import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google"
import './global.css'

const font = Roboto_Flex({ subsets: ["latin"], weight: ['400', '600', '800'] });

export const metadata: Metadata = {
  title: "root layout",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode}>) {

  return (
    <html lang="en">
      <body className={font.className}>
        {children}
      </body>
    </html>
  )
}
