import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google"
import Sidebar from "@/components/Sidebar/Sidebar"
import WorkspacesList from '../components/WorkspacesList/WorkspacesList'
import AppLogo from "@/components/AppLogo/AppLogo"
import Navigation from "@/components/Navigation/Navigation"
import ContainerFluid from "@/components/Containers/ContainerFluid"
import ContainerMain from "@/components/Containers/ContainerMain"
import TopHeader from "@/components/TopHeader/TopHeader"
import ProjectsLinkList from "@/components/ProjectsLinkList/ProjectsLinkList"
import './global.css'

const font = Roboto_Flex({ subsets: ["latin"], weight: ['400', '600', '800'] });

export const metadata: Metadata = {
  title: "Prisma",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
    children: React.ReactNode
  }>) {
    return (
      <html lang="en">
        <body className={font.className}>
          <ContainerFluid width={1400}>
            <Sidebar>
              <AppLogo/>
              <WorkspacesList/>
              <Navigation/>
              <ProjectsLinkList/>
            </Sidebar>
            
            <ContainerMain>
              <TopHeader/> 
              {children}
            </ContainerMain>
          </ContainerFluid>
        </body>
      </html>
  );
}
