import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google"
import Sidebar from "@/components/Sidebar/Sidebar"
import WorkspacesList from '../components/WorkspacesList/WorkspacesList'
import AppLogo from "@/components/AppLogo/AppLogo"
import SideNavigation from "@/components/SideNavigation/SideNavigation";
import Container from "@/components/Container/Container";
import './global.css'

const font = Roboto_Flex({ subsets: ["latin"], weight: ['400', '600', '800'] });

export const metadata: Metadata = {
  title: "Prisma",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
      <html lang="en">
        <body className={font.className}>
          <Container width={1400}>
            <Sidebar>
              <AppLogo/>
              <WorkspacesList/>
              <SideNavigation/>
            </Sidebar>
            {children}
          </Container>
        </body>
      </html>
  );
}
