import type { Metadata } from "next"

// export const metadata: Metadata = {
//     title: "authenication",
//     description: "Generated by create next app",
// };

const AuthenticationLayout = ({children}:
    { children: React.ReactNode}) => {
    return (
        <main>{children}</main>
    );
}
export default AuthenticationLayout;