import type { Metadata } from "next";
import SidebarWrapper from "@/app/(dashboard)/components/SidebarWrapper/Sidebar"
import WorkspacesList from './components/WorkspacesList/WorkspacesList'
import AppLogo from "@/app/(dashboard)/components/AppLogo/AppLogo"
import Navigation from "@/app/(dashboard)/components/Navigation/Navigation"
import ContainerFluid from "@/components/Containers/ContainerFluid"
import ContainerMain from "@/components/Containers/ContainerMain"
import TopHeader from "@/app/(dashboard)/components/TopHeader/TopHeader"
import ProjectsList from "@/app/(dashboard)/components/ProjectsList/ProjectsList"
// import { ProjectsDataType } from '../../types/tasks.types'

export const metadata: Metadata = {
  title: "dashboard",
  description: "Generated by create next app",
}

export default async function Dashboard_Layout(
  { children, modal}: { children: React.ReactNode, modal: React.ReactNode}) {
  //TODO:IN THIS PLACE ONLY PART OF DATA
  // const response = await fetch('https://jsonplaceholder.typicode.com/users')
  // const users = await response.json();
  // console.log(users);

    return (
      <ContainerFluid width={1400}>
        <SidebarWrapper>
          <AppLogo/>
          <WorkspacesList/>
          <Navigation/>
          <ProjectsList/>
        </SidebarWrapper>
        <ContainerMain>
          <TopHeader/> 
          {children}
          {modal}
        </ContainerMain>
      </ContainerFluid>
  );
}
