import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar/Sidebar"
import WorkspacesList from '../../components/WorkspacesList/WorkspacesList'
import AppLogo from "@/components/AppLogo/AppLogo"
import Navigation from "@/components/Navigation/Navigation"
import ContainerFluid from "@/components/Containers/ContainerFluid"
import ContainerMain from "@/components/Containers/ContainerMain"
import TopHeader from "@/components/TopHeader/TopHeader"
import ProjectsLinkList from "@/components/ProjectsLinkList/ProjectsLinkList"

export const metadata: Metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default async function Dashboard_Layout({ children }: Readonly<{children: React.ReactNode}>) {
  const response = await fetch('https://jsonplaceholder.typicode.com/users')
  const users = await response.json();
  console.log(users);

    return (
      <ContainerFluid width={1400}>
        <Sidebar>
          <AppLogo/>
          <WorkspacesList/>
          <Navigation/>
          <ProjectsLinkList/>
        </Sidebar>
        <ContainerMain>
          <TopHeader/> 
          {children}
        </ContainerMain>
      </ContainerFluid>
  );
}
